services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flutter_server
      POSTGRES_PASSWORD: "pci9vTwjYeNJ1fyX1INpH6u2d3bPzyBi"
    volumes:
      - flutter_server_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.20
    ports:
      - "8091:6379"
    command: redis-server --requirepass "3aFpVdCitrYYi0iVFpeN3jZ4WKmfqSnt"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flutter_server_test
      POSTGRES_PASSWORD: "WP65VfT9NK7bPmEo3NF4jTkXVQhgpM09"
    volumes:
      - flutter_server_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.20
    ports:
      - "9091:6379"
    command: redis-server --requirepass "n-0mq-D1RDuzLi5t9E-z6aU1769XCf3H"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  flutter_server_data:
  flutter_server_test_data:
